# Generated by Django 4.2.7 on 2023-11-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_pdf_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/qrcodes'),
        ),
    ]
